# Generated by Django 5.2.5 on 2025-09-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
