# Generated by Django 5.2.5 on 2025-09-08 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_botuser_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendlog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='hub.campaign'),
        ),
    ]
