# Generated by Django 5.2.5 on 2025-09-08 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_alter_sendlog_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=64, null=True)),
                ('chat_id', models.BigIntegerField()),
                ('from_user_id', models.BigIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('raw', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='hub.bot')),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='hub.botuser')),
            ],
            options={
                'indexes': [models.Index(fields=['bot', 'chat_id'], name='hub_message_bot_id_fa8454_idx'), models.Index(fields=['bot', 'received_at'], name='hub_message_bot_id_2d170e_idx')],
            },
        ),
    ]
