# Generated by Django 5.2.5 on 2025-09-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='admin_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
