# Generated by Django 5.2.5 on 2025-09-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_bot_admin_chat_id_botuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
