# Generated by Django 5.2.5 on 2025-09-14 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_candidate_campaignanalytics_dailyquestion_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='hub.bot'),
        ),
    ]
