# Generated by Django 5.2.5 on 2025-09-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_candidate_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_link',
            field=models.URLField(blank=True, help_text='Direct link to the Telegram bot (e.g., https://t.me/your_bot)', null=True),
        ),
    ]
