# Generated by Django 5.2.5 on 2025-09-14 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_bot_bot_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='candidates/gallery/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='candidates/gallery/thumbnails/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='hub.candidate')),
            ],
            options={
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
