# Generated by Django 5.2.5 on 2025-09-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_candidateuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateuser',
            name='temp_password',
            field=models.CharField(blank=True, help_text='Temporary password for display purposes only', max_length=100, null=True),
        ),
    ]
