# Generated by Django 5.2.5 on 2025-09-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_candidateuser_temp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateuser',
            name='temp_password',
        ),
    ]
