# Generated by Django 5.2.5 on 2025-09-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_remove_candidateuser_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='public_url_name',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
