# Generated by Django 5.2.5 on 2025-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0015_candidate_public_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='candidates/gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('external', 'External Link')], max_length=10),
        ),
    ]
