# Generated by Django 5.2.5 on 2025-09-18 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0017_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or short icon text, e.g., 🚀', max_length=8, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='hub.candidate')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
