# Generated by Django 5.2.5 on 2025-09-25 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0018_campaignbenefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asker_name', models.CharField(max_length=200)),
                ('asker_phone', models.CharField(max_length=32)),
                ('asker_national_id', models.CharField(blank=True, max_length=32, null=True)),
                ('question_text', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
                ('answer', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hub.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
