# Generated by Django 5.2.5 on 2025-09-25 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField()),
                ('option_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_votes', to='hub.poll')),
            ],
            options={
                'indexes': [models.Index(fields=['poll', 'user_ip'], name='hub_pollvot_poll_id_ad9d16_idx')],
                'unique_together': {('poll', 'user_ip')},
            },
        ),
    ]
